columns = [ 'course_id',
    'subj_code',
    'crse_number',
    'course_title',
    'days1',
    'times1',
    'location1',
    'term',
    'year',
    'instructor_name',
    'email',
    'phone',
    'office_location',
    'office_hours',
    'instructor_title',
    'form_of_address',
]
